### ISSUE TITLE
openid_login error

### ISSUE THREAD

**Issue by frafra** [jmflinuxtx/kerneltest-harness#22]
```
$ ./fedora_submit.py -u frafra -l $(ls -t logs/*.txt | head -1)
FAS password: 
Traceback (most recent call last):
  File "./fedora_submit.py", line 45, in <module>
    password=password
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 293, in login
    openid_insecure=self.openid_insecure)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidproxyclient.py", line 129, in openid_login
    'Un-expected openid provider asked: %s' % response.url)
fedora.client.FedoraServiceError: Un-expected openid provider asked: https://apps.fedoraproject.org/kerneltest/
```

**Comment by pypingou** [comment]
Where is the fedora-submit coming from? I'm not seeing it on github

**Comment by frafra** [comment]
I'm sorry, wrong repository. I was trying to report a bug for https://git.fedorahosted.org/cgit/kernel-tests.git/tree/ on https://bugzilla.redhat.com/ but there's no component for it.

**Comment by pypingou** [comment]
Looks like there is no right place to report bug, so I guess this is as good as any :)

**Comment by jmflinuxtx** [comment]
Yeah, bugs against the test suite should be reported to kernel@lists.fedoraproject.org But this seems to be an infrastructure thing, it started recently, but with no changes to the submit code. One day it was working, the next, it was throwing an error.  Changes were made last week, but if you go to an earlier checkout, the error still occurs.

**Comment by pypingou** [comment]
Is this ticket still valid?

**Comment by frafra** [comment]
runtests.sh can upload results properly, while fedora_submit.py shows the same error (see above); bug is still valid.

**Comment by pypingou** [comment]
On F23, I used successfully fedora_submit.py this morning :(
